CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
  `MigrationId` varchar(150) NOT NULL,
  `ProductVersion` varchar(32) NOT NULL,
  PRIMARY KEY (`MigrationId`)
);
CREATE TABLE IF NOT EXISTS users(
  id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_user_id VARCHAR(36) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(32) NOT NULL,
  status enum("LEADER", "MEMBER") NOT NULL DEFAULT "MEMBER",
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS teams(
  id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_team_id VARCHAR(36) NOT NULL,
  name VARCHAR(32) NOT NULL,
  number INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS objectives(
  id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_objective_id VARCHAR(36) NOT NULL,
  use_date TIMESTAMP NOT NULL,
  title VARCHAR(128) NOT NULL,
  content VARCHAR(225) NOT NULL,
  author VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);