FROM mcr.microsoft.com/dotnet/sdk:5.0
ENV ASPNETCORE_ENVIRONMENT=Production
WORKDIR /src
COPY teamev.api.csproj ./
RUN dotnet restore
COPY . .
RUN dotnet dev-certs https --clean && dotnet dev-certs https -t
RUN dotnet tool install --global dotnet-ef
ENV PATH $PATH:/root/.dotnet/tools

