FROM mcr.microsoft.com/dotnet/sdk:5.0
ENV ASPNETCORE_ENVIRONMENT=Development
# ENV MysqlHosts__Server="test"
WORKDIR /src
COPY teamev.api.csproj ./
RUN dotnet restore
COPY . .
RUN dotnet dev-certs https --clean && dotnet dev-certs https -t
# RUN dotnet tool install --global dotnet-ef
# ENV export PATH="$PATH:/root/.dotnet/tools"
